# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "2Y5o1/OAhT3ATfOhevXHjeKOF/oCQCQd7QfgdquVbfAIAzhkkkF5oPAOVImyjXgUpS3RBzmjvRteU/qDwG59BtrMizmGP2dZ6A7Gft/4j8l+ajxQfS+SWTOO8pmgYQ6dR5dsz/beBPaYdDr+X80O2OujX5TYMbvquQznDUlI64RjfdIsmd8BfqYlHG1DKzUm6a3wpiY5bMz1jgE+JsNsiS35M5IGksaroFOX35osZHF5Wvaci80ThLMWB9/CaWn5HH4XMRBimyzfwW8qP0mI5J0tK4GiJCA2oG5rmE5g2MWdAezwghEHkiUuWYdBJQTuErq/BnVL02lLpRnipsnDYkNuhaWWJcDoySukwnTLCQRJ+ewGCe/o5ausXQCnPZXp7Vd8UksO4e7LTddxe67zZsaUtgrKe34Phx5S3cd2SLx8z4fU+vObSv6efwVgadwbpmQaPXXzwm81L/J7QWLKPAaPndLqZmYUxgQBOLKbxMFM8LsUA14htauAdYAeH1Wj3bvQjD+BU4ln4sGUlT12PNW14RUVKe/Lj0j5XsIpmisBeAsl5mx4PNwyPRqpAvGDJEwJVD9Nm0BF0ljOiU4r+HCqqyoqcE8Ldydg5+v382uACIDGNGr2xq2H8TJm9zmgeAWCVm6o2fNzj7erth1/N2XS1oedhy135d7WYFcNYBg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
