appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: 2Y5o1/OAhT3ATfOhevXHjeKOF/oCQCQd7QfgdquVbfAIAzhkkkF5oPAOVImyjXgUpS3RBzmjvRteU/qDwG59BtrMizmGP2dZ6A7Gft/4j8l+ajxQfS+SWTOO8pmgYQ6dR5dsz/beBPaYdDr+X80O2OujX5TYMbvquQznDUlI64RjfdIsmd8BfqYlHG1DKzUm6a3wpiY5bMz1jgE+JsNsiS35M5IGksaroFOX35osZHF5Wvaci80ThLMWB9/CaWn5HH4XMRBimyzfwW8qP0mI5J0tK4GiJCA2oG5rmE5g2MWdAezwghEHkiUuWYdBJQTuErq/BnVL02lLpRnipsnDYkNuhaWWJcDoySukwnTLCQRJ+ewGCe/o5ausXQCnPZXp7Vd8UksO4e7LTddxe67zZsaUtgrKe34Phx5S3cd2SLx8z4fU+vObSv6efwVgadwbpmQaPXXzwm81L/J7QWLKPAaPndLqZmYUxgQBOLKbxMFM8LsUA14htauAdYAeH1Wj3bvQjD+BU4ln4sGUlT12PNW14RUVKe/Lj0j5XsIpmisBeAsl5mx4PNwyPRqpAvGDJEwJVD9Nm0BF0ljOiU4r+HCqqyoqcE8Ldydg5+v382uACIDGNGr2xq2H8TJm9zmgeAWCVm6o2fNzj7erth1/N2XS1oedhy135d7WYFcNYBg=
